version: "3.5"
services:
  nginx:
    depends_on:
      - site_1
      - site_2
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
  site_1:
    container_name: site_1
    build:
      dockerfile: Dockerfile
      context: ./site-1
  site_2:
    container_name: site_2
    build:
      dockerfile: Dockerfile
      context: ./site-2
